services:
  app:
    build:
      context: .
    image: my-node-app
    ports:
      - "${APP_PORT}:${APP_PORT_CONTAINER}"
    env_file:
      - .env.${NODE_ENV}
    depends_on:
      - db
    volumes:
      - .:/usr/src/app

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: